import { LaunchDemo } from "./schema";

function esc(v:any) {
  return String(v ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
}

export function renderLaunchHtml(demo:LaunchDemo) {
  const themeStyles:any = {
    apple:{bg:"#f8fafc", text:"#0f172a", muted:"#64748b", accent:"#111827", surface:"rgba(255,255,255,.78)", border:"rgba(15,23,42,.10)", glow:"rgba(15,23,42,.12)"},
    luxury:{bg:"#050505", text:"#ffffff", muted:"rgba(255,255,255,.58)", accent:"#d4af37", surface:"rgba(255,255,255,.045)", border:"rgba(212,175,55,.25)", glow:"rgba(212,175,55,.22)"},
    fintech:{bg:"#020617", text:"#ffffff", muted:"rgba(255,255,255,.60)", accent:"#22d3ee", surface:"rgba(8,47,73,.28)", border:"rgba(34,211,238,.25)", glow:"rgba(34,211,238,.22)"},
    construction:{bg:"#0c0a09", text:"#fff7ed", muted:"rgba(255,237,213,.62)", accent:"#f97316", surface:"rgba(154,52,18,.20)", border:"rgba(249,115,22,.25)", glow:"rgba(249,115,22,.22)"},
    startup:{bg:"#02040a", text:"#ffffff", muted:"rgba(255,255,255,.58)", accent:"#3b82f6", surface:"rgba(59,130,246,.10)", border:"rgba(59,130,246,.25)", glow:"rgba(59,130,246,.24)"},
    enterprise:{bg:"#0f172a", text:"#ffffff", muted:"rgba(255,255,255,.60)", accent:"#8b5cf6", surface:"rgba(255,255,255,.055)", border:"rgba(139,92,246,.25)", glow:"rgba(139,92,246,.24)"}
  };

  const theme = themeStyles[(demo as any).theme] || themeStyles.startup;
  const accent = theme.accent;

  const sections = (demo.sections || []).map((s:any, index:number) => {
    const delay = Math.min(index * 80, 500);

    if (s.type === "hero") {
      return `
<section class="hero reveal" style="--d:${delay}ms">
  <div class="orb orb-a"></div>
  <div class="orb orb-b"></div>
  <div class="pill">${esc(s.eyebrow || "AI GENERATED PRESENTATION")}</div>
  <h1>${esc(s.headline || demo.title)}</h1>
  <p class="lead">${esc(s.subheadline || "A futuristic business presentation generated by ALMA Launch Studio.")}</p>
  <div class="actions"><button>Start Presentation</button><button class="ghost">View Details</button></div>
</section>`;
    }

    if (s.type === "mock_dashboard") {
      const rows = (s.rows || []).map((r:any) => `<tr><td>${esc(r[0])}</td><td>${esc(r[1])}</td><td class="accent">${esc(r[2])}</td><td class="green">${esc(r[3])}</td></tr>`).join("");
      return `
<section class="panel reveal" style="--d:${delay}ms">
  <div class="panel-head"><strong>${esc(s.title || "Live Product Preview")}</strong><span>ONLINE</span></div>
  <table><tbody>${rows}</tbody></table>
</section>`;
    }

    if (s.type === "features") {
      const cards = (s.cards || []).map((c:any) => `<div class="card"><div class="dot"></div><h3>${esc(c.title)}</h3><p>${esc(c.description)}</p></div>`).join("");
      return `<section class="reveal" style="--d:${delay}ms"><h2>${esc(s.title || "Premium features")}</h2><div class="grid">${cards}</div></section>`;
    }

    if (s.type === "stats") {
      const stats = (s.stats || []).map((x:any) => `<div class="stat"><small>${esc(x[0])}</small><strong>${esc(x[1])}</strong></div>`).join("");
      return `<section class="reveal" style="--d:${delay}ms"><h2>${esc(s.title || "Proof in numbers")}</h2><div class="stats">${stats}</div></section>`;
    }

    if (s.type === "pricing") {
      const plans = (s.plans || []).map((p:any) => `<div class="card price-card"><h3>${esc(p.name)}</h3><strong class="price">${esc(p.price)}</strong><p>${(p.features || []).map((f:string)=>"? "+esc(f)).join("<br>")}</p></div>`).join("");
      return `<section class="reveal" style="--d:${delay}ms"><h2>${esc(s.title || "Choose your path")}</h2><div class="grid">${plans}</div></section>`;
    }

    return `<section class="cta reveal" style="--d:${delay}ms"><h2>${esc(s.headline || s.title || "Ready to launch?")}</h2><p>${esc(s.subheadline || s.description || "")}</p><button>Get Started</button></section>`;
  }).join("");

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>${esc(demo.title || "ALMA Launch Studio")}</title>
<style>
*{box-sizing:border-box}
html{scroll-behavior:smooth}
body{margin:0;background:${theme.bg};color:${theme.text};font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;overflow-x:hidden}
body:before{content:"";position:fixed;inset:0;background:linear-gradient(to right,rgba(255,255,255,.045) 1px,transparent 1px),linear-gradient(to bottom,rgba(255,255,255,.045) 1px,transparent 1px);background-size:64px 64px;mask-image:linear-gradient(to bottom,#000 0%,transparent 72%);pointer-events:none}
body:after{content:"";position:fixed;top:-260px;left:50%;width:850px;height:850px;transform:translateX(-50%);background:${accent};opacity:.18;filter:blur(150px);border-radius:999px;pointer-events:none;animation:floatGlow 8s ease-in-out infinite alternate}
nav{position:sticky;top:18px;z-index:10;max-width:1180px;margin:18px auto 0;padding:14px 18px;border:1px solid ${theme.border};background:${theme.surface};backdrop-filter:blur(28px);border-radius:999px;display:flex;align-items:center;justify-content:space-between;box-shadow:0 20px 70px ${theme.glow}}
nav strong{letter-spacing:-.04em}.navlinks{display:flex;gap:28px;color:${theme.muted};font-size:14px}.join{background:${theme.text};color:${theme.bg};border:0;border-radius:999px;padding:11px 18px;font-weight:800}
main{position:relative;z-index:1;max-width:1180px;margin:0 auto;padding:70px 22px}
.hero{position:relative;min-height:680px;display:flex;flex-direction:column;align-items:flex-start;justify-content:center}
.orb{position:absolute;border-radius:999px;filter:blur(30px);opacity:.38;pointer-events:none}.orb-a{right:8%;top:18%;width:220px;height:220px;background:${accent};animation:floatA 7s ease-in-out infinite}.orb-b{right:24%;bottom:18%;width:120px;height:120px;background:#fff;opacity:.08;animation:floatB 9s ease-in-out infinite}
.pill{display:inline-flex;border:1px solid color-mix(in srgb, ${accent} 45%, transparent);background:color-mix(in srgb, ${accent} 16%, transparent);color:${accent};border-radius:999px;padding:9px 14px;font-size:12px;font-weight:900;letter-spacing:.2em}
h1{font-size:clamp(52px,8.8vw,120px);line-height:.84;margin:24px 0 18px;letter-spacing:-.085em;max-width:1000px;background:linear-gradient(90deg,${theme.text},${accent});-webkit-background-clip:text;color:transparent}
h2{font-size:clamp(34px,5.2vw,68px);letter-spacing:-.065em;text-align:center;margin:0 0 26px}
h3{font-size:22px;letter-spacing:-.035em;margin:0 0 10px}
p{color:${theme.muted};font-size:17px;line-height:1.75}.lead{font-size:21px;max-width:760px}
.actions{display:flex;flex-wrap:wrap;gap:14px;margin-top:28px}
button{background:${accent};color:#02040a;border:0;border-radius:999px;padding:15px 24px;font-weight:900;box-shadow:0 0 50px color-mix(in srgb, ${accent} 38%, transparent)}
.ghost{background:rgba(255,255,255,.06);color:${theme.text};border:1px solid ${theme.border};box-shadow:none}
section{margin:95px 0}
.panel{border:1px solid color-mix(in srgb, ${accent} 35%, transparent);background:linear-gradient(135deg,rgba(255,255,255,.10),rgba(255,255,255,.025));border-radius:34px;overflow:hidden;box-shadow:0 0 100px color-mix(in srgb, ${accent} 18%, transparent);transform-style:preserve-3d}
.panel-head{display:flex;justify-content:space-between;align-items:center;padding:20px 24px;border-bottom:1px solid ${theme.border};font-size:13px}.panel-head span{color:${accent};font-size:11px;letter-spacing:.22em}
table{width:100%;border-collapse:collapse}td{padding:18px 24px;border-bottom:1px solid ${theme.border};font-weight:700;color:${theme.muted}}.accent{color:${accent}}.green{color:#34d399}
.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card,.stat{position:relative;border:1px solid ${theme.border};background:${theme.surface};border-radius:28px;padding:28px;backdrop-filter:blur(20px);transition:transform .25s ease,border-color .25s ease,box-shadow .25s ease}.card:hover,.stat:hover{transform:translateY(-6px);border-color:${accent};box-shadow:0 24px 80px ${theme.glow}}
.dot{width:11px;height:11px;border-radius:999px;background:${accent};box-shadow:0 0 24px ${accent};margin-bottom:24px}.card p{font-size:15px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.stat small{color:${theme.muted};text-transform:uppercase;letter-spacing:.18em}.stat strong{display:block;margin-top:10px;font-size:34px}.price{display:block;font-size:40px;color:${accent};margin:10px 0 18px}
.cta{text-align:center;border:1px solid ${theme.border};background:radial-gradient(circle at top, color-mix(in srgb, ${accent} 22%, transparent), rgba(255,255,255,.035));border-radius:40px;padding:76px 30px}.cta p{margin:0 auto 28px;max-width:700px}
.reveal{opacity:0;transform:translateY(28px);animation:reveal .8s cubic-bezier(.16,1,.3,1) forwards;animation-delay:var(--d)}
@keyframes reveal{to{opacity:1;transform:translateY(0)}}@keyframes floatGlow{to{transform:translateX(-50%) translateY(40px);opacity:.28}}@keyframes floatA{50%{transform:translateY(-28px) translateX(18px)}}@keyframes floatB{50%{transform:translateY(24px) translateX(-20px)}}
@media(max-width:800px){nav{left:12px;right:12px;margin:12px}.navlinks{display:none}.grid,.stats{grid-template-columns:1fr}.hero{min-height:auto;padding-top:70px}td{font-size:12px;padding:14px 10px}main{padding:44px 16px}section{margin:65px 0}}
</style>
</head>
<body>
<nav><strong>${esc(demo.title || "ALMA")}</strong><div class="navlinks">${(demo.nav || []).map((n:any)=>`<span>${esc(n)}</span>`).join("")}</div><button class="join">Launch</button></nav>
<main>${sections}</main>
</body>
</html>`;
}
