"use client";

import { ArrowUp, Camera, Mic, Paperclip } from "lucide-react";
import { type Dispatch, type SetStateAction, useEffect, useRef, useState } from "react";

export type ChatLanguage = "en" | "es";
export type ChatMessage = { id: string; role: "user" | "assistant"; content: string; status?: "streaming" | "error" };

type Copy = {
  greeting: string; identity: string; subtitle: string; prompt: string; disclaimer: string;
  thinking: string; networkError: string; responseError: string; interrupted: string;
  chipImage: string; chipLogo: string; chipAd: string; chipCode: string;
};

const copy: Record<ChatLanguage, Copy> = {
  en: { greeting: "Good morning.", identity: "I am ALMA.", subtitle: "Chat, images, documents, code, and automation in one place.", prompt: "Ask ALMA to create, edit, write, or build...", disclaimer: "ALMA can make mistakes. Verify important information.", thinking: "ALMA is thinking…", networkError: "ALMA could not reach the server. Please try again.", responseError: "ALMA could not start a response.", interrupted: "Response interrupted. Please try again.", chipImage: "Create a premium image", chipLogo: "Make a logo", chipAd: "Generate a 16:9 ad", chipCode: "Write code" },
  es: { greeting: "Buenos días.", identity: "Soy ALMA.", subtitle: "Chat, imágenes, documentos, código y automatización en un solo lugar.", prompt: "Pídele a ALMA crear, editar, escribir o construir...", disclaimer: "ALMA puede cometer errores. Verifica información importante.", thinking: "ALMA está pensando…", networkError: "ALMA no pudo conectarse al servidor. Inténtalo de nuevo.", responseError: "ALMA no pudo iniciar una respuesta.", interrupted: "La respuesta se interrumpió. Inténtalo de nuevo.", chipImage: "Crea una imagen premium", chipLogo: "Haz un logo", chipAd: "Genera un anuncio 16:9", chipCode: "Escribe código" },
};

const newId = () => globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`;
const requestedLanguage = (message: string): ChatLanguage | null => /\b(en español|en espanol|spanish)\b/i.test(message) ? "es" : /\b(in english|en inglés|en ingles)\b/i.test(message) ? "en" : null;

function MessageContent({ content }: { content: string }) {
  const image = content.match(/\[ALMA_IMAGE:(.*?)\]/)?.[1];
  if (image) return <img src={`data:image/png;base64,${image}`} className="max-h-[70vh] w-full rounded-2xl border border-[#E5E7EB] object-contain shadow-sm" alt="ALMA generated image" />;
  const segments = content.split(/(```[\s\S]*?```)/g);
  return <div className="min-w-0 break-words whitespace-pre-wrap leading-7">{segments.map((segment, index) => segment.startsWith("```") ? <pre key={index} className="my-3 max-w-full overflow-x-auto rounded-xl bg-neutral-900 p-4 text-sm leading-6 text-neutral-100"><code>{segment.slice(3, -3).trim()}</code></pre> : segment)}</div>;
}

export function ChatMessageList({ messages, language }: { messages: ChatMessage[]; language: ChatLanguage }) {
  return <div className="mx-auto w-full max-w-3xl space-y-5 px-4 py-8 md:px-6 md:py-12">{messages.length === 0 ? <div className="mt-20 text-center md:mt-28"><h1 className="mb-2 text-3xl font-normal tracking-tight md:text-4xl">{copy[language].greeting}</h1><h2 className="mb-4 text-3xl font-normal tracking-tight md:text-4xl">{copy[language].identity}</h2><p className="text-lg text-[#6B7280]">{copy[language].subtitle}</p></div> : messages.map((message) => <div key={message.id} className={message.role === "user" ? "ml-auto w-fit max-w-full rounded-2xl bg-black p-3 text-sm text-white md:max-w-[80%] md:p-4" : "max-w-full rounded-2xl border border-[#E5E7EB] bg-[#F7F7F8] p-3 text-sm md:max-w-[88%] md:p-4"}>{message.status === "streaming" && !message.content ? <div className="flex items-center gap-2 text-[#6B7280]"><span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-neutral-300 border-t-black" />{copy[language].thinking}</div> : <MessageContent content={message.content} />}</div>)}</div>;
}

export function ChatSuggestions({ language, onSelect }: { language: ChatLanguage; onSelect: (value: string) => void }) {
  const t = copy[language];
  return <div className="mx-auto flex w-full max-w-3xl gap-2 overflow-x-auto px-4 pt-3 md:flex-wrap md:px-6">{[t.chipImage, t.chipLogo, t.chipAd, t.chipCode].map((label) => <button key={label} type="button" onClick={() => onSelect(label)} className="shrink-0 rounded-full border border-[#E5E7EB] bg-[#F7F7F8] px-3 py-1.5 text-xs font-medium text-[#6B7280] hover:text-black">{label}</button>)}</div>;
}

export function ChatComposer({ value, language, busy, onChange, onSend, onFile }: { value: string; language: ChatLanguage; busy: boolean; onChange: (value: string) => void; onSend: () => void; onFile: (file: File) => void }) {
  const fileRef = useRef<HTMLInputElement>(null); const cameraRef = useRef<HTMLInputElement>(null);
  return <div className="border-t border-[#E5E7EB] bg-white px-3 pb-[max(1rem,env(safe-area-inset-bottom))] pt-3 md:px-6"><div className="mx-auto w-full max-w-3xl"><div className="relative flex flex-col overflow-hidden rounded-2xl border border-[#E5E7EB] bg-[#F7F7F8] shadow-sm"><textarea value={value} disabled={busy} onChange={(event) => onChange(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); onSend(); } }} rows={1} placeholder={copy[language].prompt} className="min-h-28 max-h-44 w-full resize-none bg-transparent px-4 pb-14 pt-4 pr-14 text-base leading-6 outline-none placeholder:text-gray-400 disabled:opacity-60" /><div className="absolute bottom-3 left-3 flex items-center gap-1"><input ref={fileRef} type="file" className="hidden" accept="image/*,.pdf,.docx,.txt,.csv,.xlsx,.xls" onChange={(event) => { const file = event.target.files?.[0]; if (file) onFile(file); event.currentTarget.value = ""; }} /><input ref={cameraRef} type="file" className="hidden" accept="image/*" capture="environment" onChange={(event) => { const file = event.target.files?.[0]; if (file) onFile(file); event.currentTarget.value = ""; }} /><button type="button" disabled={busy} onClick={() => fileRef.current?.click()} className="rounded-md p-1 text-[#6B7280] hover:bg-gray-200 hover:text-black"><Paperclip className="h-5 w-5" /></button><button type="button" disabled={busy} onClick={() => cameraRef.current?.click()} className="rounded-md p-1 text-[#6B7280] hover:bg-gray-200 hover:text-black"><Camera className="h-5 w-5" /></button><Mic className="h-5 w-5 p-0.5 text-[#6B7280]" /></div><button type="button" onClick={onSend} disabled={busy || !value.trim()} className="absolute bottom-3 right-3 rounded-lg bg-black p-1.5 text-white hover:bg-gray-800 disabled:opacity-40"><ArrowUp className="h-5 w-5" /></button></div><p className="pt-2 text-center text-[10px] text-gray-400">{copy[language].disclaimer}</p></div></div>;
}

export default function ChatWorkspace({ messages, setMessages, conversationId, setConversationId, language, setLanguage, streamEpoch, loadingConversation, onComplete, onAnalyzeFile }: { messages: ChatMessage[]; setMessages: Dispatch<SetStateAction<ChatMessage[]>>; conversationId: string | null; setConversationId: (id: string) => void; language: ChatLanguage; setLanguage: (language: ChatLanguage) => void; streamEpoch: number; loadingConversation: boolean; onComplete: () => void; onAnalyzeFile: (file: File) => void }) {
  const [input, setInput] = useState(""); const [busy, setBusy] = useState(false); const sending = useRef(false); const controller = useRef<AbortController | null>(null); const messageArea = useRef<HTMLDivElement>(null); const shouldStick = useRef(true);
  useEffect(() => () => controller.current?.abort(), []);
  useEffect(() => { controller.current?.abort(); }, [streamEpoch]);
  useEffect(() => { if (shouldStick.current) messageArea.current?.scrollTo({ top: messageArea.current.scrollHeight, behavior: busy ? "auto" : "smooth" }); }, [messages, busy]);
  const send = async () => { if (sending.current || !input.trim()) return; const prompt = input.trim(); const responseLanguage = requestedLanguage(prompt) ?? language; if (responseLanguage !== language) setLanguage(responseLanguage); const user: ChatMessage = { id: newId(), role: "user", content: prompt }; const draftId = newId(); let streamed = ""; sending.current = true; setBusy(true); setInput(""); setMessages((current) => [...current, user, { id: draftId, role: "assistant", content: "", status: "streaming" }]); controller.current = new AbortController(); try { const response = await fetch("/api/chat/stream", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: prompt, conversationId, language: responseLanguage }), signal: controller.current.signal }); if (!response.ok || !response.body) { setMessages((current) => current.map((message) => message.id === draftId ? { ...message, content: copy[responseLanguage].responseError, status: "error" } : message)); return; } const reader = response.body.getReader(); const decoder = new TextDecoder(); while (true) { const { value, done } = await reader.read(); if (done) break; const chunk = decoder.decode(value, { stream: true }); const match = chunk.match(/\[CONVERSATION_ID:(.*?)\]\n/); if (match?.[1]) setConversationId(match[1]); streamed += chunk.replace(/\[CONVERSATION_ID:.*?\]\n/, ""); setMessages((current) => current.map((message) => message.id === draftId ? { ...message, content: streamed, status: "streaming" } : message)); } streamed += decoder.decode(); setMessages((current) => current.map((message) => message.id === draftId ? { ...message, content: streamed, status: undefined } : message)); } catch (error) { const content = streamed || (error instanceof DOMException && error.name === "AbortError" ? copy[responseLanguage].interrupted : copy[responseLanguage].networkError); setMessages((current) => current.map((message) => message.id === draftId ? { ...message, content, status: "error" } : message)); } finally { controller.current = null; sending.current = false; setBusy(false); onComplete(); } };
  return <div className="flex min-h-0 flex-1 flex-col bg-white"><div ref={messageArea} onScroll={(event) => { const element = event.currentTarget; shouldStick.current = element.scrollHeight - element.scrollTop - element.clientHeight < 96; }} className="min-h-0 flex-1 overflow-y-auto">{loadingConversation ? <div className="mx-auto flex h-full max-w-3xl items-center px-4 text-sm text-[#6B7280]">{language === "es" ? "Cargando conversación…" : "Loading conversation…"}</div> : <ChatMessageList messages={messages} language={language} />}</div>{messages.length === 0 && !loadingConversation && <ChatSuggestions language={language} onSelect={setInput} />}<ChatComposer value={input} language={language} busy={busy || loadingConversation} onChange={setInput} onSend={send} onFile={onAnalyzeFile} /></div>;
}
