export const DASHBOARD_ROUTE = "/dashboard";

export const WORKSPACE_ROUTES = {
  customers: "/customers",
  inbox: "/inbox",
  work: "/work",
  money: "/money",
  automations: "/automations",
  knowledge: "/knowledge",
  business_launch: "/business-launch",
  reports: "/reports",
  approvals: "/approvals",
  files: "/files",
  apps: "/dashboard/apps",
  connections: "/connections",
  communications: "/communications",
  translator: "/translator",
  voice_agents: "/voice-agents",
  office: "/office",
  tasks: "/tasks",
  notes: "/notes",
  planner: "/planner",
  documents: "/documents",
  fitness: "/fitness",
  crm: "/crm",
  construction: "/construction",
  invoicing: "/invoicing",
  images: "/images",
  creative: "/creative",
  launch: "/launch-studio",
  trader: "/trader",
  agents: "/agents",
  builder: "/builder",
  marketplace: "/marketplace",
  billing: "/billing",
  settings: "/settings",
  workspaces: "/workspaces",
} as const;

export type RoutedWorkspace = keyof typeof WORKSPACE_ROUTES;
