import { NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth/user";
import { createClient } from "@/lib/supabase/server";
import { calculateInvoiceTotals, invoiceStatuses, numberValue } from "@/lib/services/invoicing/invoiceService";
const transitions: Record<string, string[]> = { draft:["sent","cancelled"], sent:["viewed","paid","overdue","cancelled"], viewed:["paid","overdue","cancelled"], overdue:["paid","cancelled"] };
const draftFields = ["client_name","client_email","client_phone","billing_address","issue_date","due_date","currency","notes","terms"] as const;
export async function GET(_request: Request, context: { params: Promise<{ id: string }> }) { const user = await getCurrentUser(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const id = (await context.params).id; const supabase = await createClient(); const { data, error } = await supabase.from("invoices").select("*,invoice_line_items(*)").eq("id", id).eq("user_id", user.id).maybeSingle(); return error || !data ? NextResponse.json({ error: "Not found" }, { status: 404 }) : NextResponse.json(data); }
export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) { const user = await getCurrentUser(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const id = (await context.params).id; const body = await request.json(); const supabase = await createClient(); const { data: current } = await supabase.from("invoices").select("*").eq("id", id).eq("user_id", user.id).maybeSingle(); if (!current) return NextResponse.json({ error: "Not found" }, { status: 404 }); const patch: Record<string, unknown> = {};
 if (body.status) { if (!invoiceStatuses.includes(body.status) || !(transitions[current.status] ?? []).includes(body.status)) return NextResponse.json({ error: "Invalid status transition" }, { status: 400 }); patch.status=body.status; if(body.status==="sent")patch.sent_at=new Date().toISOString(); if(body.status==="viewed")patch.viewed_at=new Date().toISOString(); if(body.status==="paid")patch.paid_at=new Date().toISOString(); }
 const wantsDraftEdit = draftFields.some((key) => body[key] !== undefined) || body.taxRate !== undefined || body.discountRate !== undefined;
 if (wantsDraftEdit) { if (current.status !== "draft") return NextResponse.json({ error: "Only drafts can be edited" }, { status: 400 }); for (const key of draftFields) if (body[key] !== undefined) patch[key] = body[key] || null; if (body.currency) patch.currency=String(body.currency).toUpperCase(); const { data: lines } = await supabase.from("invoice_line_items").select("quantity,unit_price").eq("invoice_id", id).eq("user_id", user.id); const subtotal=(lines ?? []).reduce((sum,line)=>sum+numberValue(line.quantity)*numberValue(line.unit_price),0); const taxRate=body.taxRate===undefined ? (subtotal ? numberValue(current.tax_amount)*100/subtotal : 0) : numberValue(body.taxRate); const discountRate=body.discountRate===undefined ? (subtotal ? numberValue(current.discount_amount)*100/subtotal : 0) : numberValue(body.discountRate); const totals=calculateInvoiceTotals(lines ?? [],taxRate,discountRate); Object.assign(patch,{subtotal:totals.subtotal,tax_amount:totals.taxAmount,discount_amount:totals.discountAmount,total:totals.total,amount:totals.total}); }
 if (!Object.keys(patch).length) return NextResponse.json({ error: "No supported changes" }, { status: 400 }); const { data, error } = await supabase.from("invoices").update(patch).eq("id", id).eq("user_id", user.id).select().single(); return error ? NextResponse.json({ error: "Invoice could not be updated" }, { status: 400 }) : NextResponse.json(data); }
export async function DELETE(_request: Request, context: { params: Promise<{ id: string }> }) { const user = await getCurrentUser(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const id=(await context.params).id; const supabase=await createClient(); const {data}=await supabase.from("invoices").select("status").eq("id",id).eq("user_id",user.id).maybeSingle(); if(!data||data.status!=="draft")return NextResponse.json({error:"Only drafts can be deleted"},{status:400}); const {error}=await supabase.from("invoices").delete().eq("id",id).eq("user_id",user.id); return error?NextResponse.json({error:"Invoice could not be deleted"},{status:400}):NextResponse.json({success:true}); }
