import { createClient } from "@/lib/supabase/server";
import { createInvoiceNumber, numberValue, recalculateInvoiceTotals } from "@/lib/services/invoicing/invoiceService";

export async function crmTool(userId:string, action:string, input:any, executionId?:string) { const s=await createClient();
 if(action==="create_contact"){if(executionId){const{data}=await s.from("contacts").select("*").eq("user_id",userId).eq("source","alma_chat").eq("source_execution_id",executionId).maybeSingle();if(data)return {success:true,contact:data};}const{data,error}=await s.from("contacts").insert({user_id:userId,name:String(input.name).trim(),email:input.email||null,phone:input.phone||null,company:input.company||null,source:executionId?"alma_chat":"manual",source_execution_id:executionId??null}).select().single();return error?{success:false,message:"Contact could not be saved."}:{success:true,contact:data};}
 if(action==="create_company"){if(executionId){const{data}=await s.from("companies").select("*").eq("user_id",userId).eq("source","alma_chat").eq("source_execution_id",executionId).maybeSingle();if(data)return{success:true,company:data};}const{data,error}=await s.from("companies").insert({user_id:userId,name:String(input.name).trim(),website:input.website||null,source:executionId?"alma_chat":"manual",source_execution_id:executionId??null}).select().single();return error?{success:false,message:"Company could not be saved."}:{success:true,company:data};}
 if(action==="create_opportunity"){if(executionId){const{data}=await s.from("opportunities").select("*").eq("user_id",userId).eq("source","alma_chat").eq("source_execution_id",executionId).maybeSingle();if(data)return{success:true,opportunity:data};}const{data,error}=await s.from("opportunities").insert({user_id:userId,title:String(input.title).trim(),stage:input.stage||"lead",value:input.value??null,source:executionId?"alma_chat":"manual",source_execution_id:executionId??null}).select().single();return error?{success:false,message:"Opportunity could not be saved."}:{success:true,opportunity:data};}
 if(action==="list_crm"){const [contacts,companies,opportunities]=await Promise.all([s.from("contacts").select("*").eq("user_id",userId).limit(20),s.from("companies").select("*").eq("user_id",userId).limit(20),s.from("opportunities").select("*").eq("user_id",userId).limit(20)]);return{success:true,contacts:contacts.data??[],companies:companies.data??[],opportunities:opportunities.data??[]};}
 if(action==="update_opportunity_stage"){const{data,error}=await s.from("opportunities").update({stage:input.stage}).eq("id",input.id).eq("user_id",userId).select().single();return error?{success:false,message:"Opportunity not found."}:{success:true,opportunity:data};}
 if(action==="create_crm_activity"){const type=input.type||"note";if(executionId){const{data}=await s.from("crm_activities").select("*").eq("user_id",userId).eq("source_execution_id",executionId).eq("activity_type",type).maybeSingle();if(data)return{success:true,activity:data};}const{data,error}=await s.from("crm_activities").insert({user_id:userId,opportunity_id:input.opportunityId||null,contact_id:input.contactId||null,company_id:input.companyId||null,activity_type:type,content:String(input.content).trim(),source_execution_id:executionId??null}).select().single();return error?{success:false,message:"Activity could not be saved."}:{success:true,activity:data};}
 return {success:false,message:"Unsupported CRM action."}; }

async function ownedInvoice(s:any,userId:string,invoiceNumber:string){const{data}=await s.from("invoices").select("*").eq("user_id",userId).eq("invoice_number",invoiceNumber).maybeSingle();return data;}
export async function invoiceTool(userId:string,action:string,input:any,executionId?:string){const s=await createClient();
 if(action==="create_invoice"){if(executionId){const{data}=await s.from("invoices").select("*").eq("user_id",userId).eq("source","alma_chat").eq("source_execution_id",executionId).maybeSingle();if(data)return{success:true,invoice:data};}const total=Math.max(0,numberValue(input.amount));const{data,error}=await s.from("invoices").insert({user_id:userId,invoice_number:createInvoiceNumber(),client_name:String(input.clientName).trim(),currency:input.currency||"USD",status:"draft",subtotal:total,total,amount:total,source:executionId?"alma_chat":"manual",source_execution_id:executionId??null}).select().single();return error?{success:false,message:"Invoice could not be saved."}:{success:true,invoice:data};}
 if(action==="add_invoice_item"){const invoice=await ownedInvoice(s,userId,String(input.invoiceNumber));if(!invoice||invoice.status!=="draft")return{success:false,message:"Draft invoice not found."};const key=executionId?`${executionId}:add-item` : null;if(key){const{data}=await s.from("invoice_line_items").select("*").eq("invoice_id",invoice.id).eq("idempotency_key",key).maybeSingle();if(data)return{success:true,item:data};}const q=Math.max(1,numberValue(input.quantity,1)),p=Math.max(0,numberValue(input.unitPrice));const{data,error}=await s.from("invoice_line_items").insert({invoice_id:invoice.id,user_id:userId,description:String(input.description).trim(),quantity:q,unit_price:p,line_total:q*p,idempotency_key:key,source_execution_id:executionId??null}).select().single();if(error)return{success:false,message:"Line item could not be saved."};await recalculateInvoiceTotals(userId,invoice.id);return{success:true,item:data};}
 if(action==="update_invoice_item"){const invoice=await ownedInvoice(s,userId,String(input.invoiceNumber));if(!invoice||invoice.status!=="draft")return{success:false,message:"Draft invoice not found."};const q=Math.max(1,numberValue(input.quantity,1)),p=Math.max(0,numberValue(input.unitPrice));const{data,error}=await s.from("invoice_line_items").update({description:String(input.description).trim(),quantity:q,unit_price:p,line_total:q*p}).eq("id",input.itemId).eq("invoice_id",invoice.id).eq("user_id",userId).select().single();if(error)return{success:false,message:"Line item not found."};await recalculateInvoiceTotals(userId,invoice.id);return{success:true,item:data};}
 if(action==="set_invoice_amounts"){const invoice=await ownedInvoice(s,userId,String(input.invoiceNumber));if(!invoice||invoice.status!=="draft")return{success:false,message:"Draft invoice not found."};const{data:lines}=await s.from("invoice_line_items").select("quantity,unit_price").eq("invoice_id",invoice.id).eq("user_id",userId);const subtotal=(lines??[]).reduce((n:number,l:any)=>n+numberValue(l.quantity)*numberValue(l.unit_price),0);const tax=Math.max(0,subtotal*numberValue(input.taxRate)/100),discount=Math.max(0,subtotal*numberValue(input.discountRate)/100);const{data,error}=await s.from("invoices").update({tax_amount:tax,discount_amount:discount,subtotal,total:Math.max(0,subtotal+tax-discount),amount:Math.max(0,subtotal+tax-discount),due_date:input.dueDate??invoice.due_date}).eq("id",invoice.id).eq("user_id",userId).select().single();return error?{success:false,message:"Invoice could not be updated."}:{success:true,invoice:data};}
 if(action==="list_unpaid_invoices"){const{data}=await s.from("invoices").select("*").eq("user_id",userId).in("status",["draft","sent","viewed","overdue"]).order("due_date");return{success:true,invoices:data??[]};}
 if(action==="get_invoice"){const invoice=await ownedInvoice(s,userId,String(input.invoiceNumber));return invoice?{success:true,invoice}:{success:false,message:"Invoice not found."};}
 if(action==="mark_invoice_paid"||action==="cancel_invoice"){const invoice=await ownedInvoice(s,userId,String(input.invoiceNumber));if(!invoice)return{success:false,message:"Invoice not found."};const status=action==="mark_invoice_paid"?"paid":"cancelled";const{data,error}=await s.from("invoices").update({status,paid_at:status==="paid"?new Date().toISOString():null}).eq("id",invoice.id).eq("user_id",userId).select().single();return error?{success:false,message:"Invoice could not be updated."}:{success:true,invoice:data};}
 if(action==="duplicate_invoice"){const source=await ownedInvoice(s,userId,String(input.invoiceNumber));if(!source)return{success:false,message:"Invoice not found."};const duplicateKey=executionId?`${source.id}:${executionId}`:null;if(duplicateKey){const{data}=await s.from("invoices").select("*").eq("user_id",userId).eq("duplicate_key",duplicateKey).maybeSingle();if(data)return{success:true,invoice:data};}const{data,error}=await s.from("invoices").insert({user_id:userId,invoice_number:createInvoiceNumber(),client_name:source.client_name,client_email:source.client_email,client_phone:source.client_phone,billing_address:source.billing_address,due_date:source.due_date,currency:source.currency,subtotal:source.subtotal,tax_amount:source.tax_amount,discount_amount:source.discount_amount,total:source.total,amount:source.total,notes:source.notes,terms:source.terms,status:"draft",source:"duplicate",duplicate_key:duplicateKey}).select().single();return error?{success:false,message:"Invoice could not be duplicated."}:{success:true,invoice:data};}
 return{success:false,message:"Unsupported invoice action."}; }
