import { listTrader, saveTrader } from "@/lib/trader/repository";
export async function traderTool(userId:string,name:string,args:any,executionId?:string) {
  const key=executionId?`${executionId}:${name}:${String(args.symbol??"").toUpperCase()}`:undefined;
  if(name==="add_to_watchlist") { const symbol=String(args.symbol??"").trim().toUpperCase(); if(!/^[A-Z0-9.:-]{1,24}$/.test(symbol)) return {success:false,message:"A valid symbol is required."}; const item=await saveTrader(userId,"watchlist",{symbol,notes:args.notes??null,asset_type:args.assetType??"equity",source_execution_id:executionId,idempotency_key:key}); return {success:true,message:`Added ${symbol} to your watchlist.`,item}; }
  if(name==="list_watchlist") { const items=await listTrader(userId,"watchlist"); return {success:true,message:items.length?items.map((item:any)=>item.symbol).join(", "):"Your watchlist is empty.",items}; }
  if(name==="create_trading_journal_entry") { const symbol=String(args.symbol??"").trim().toUpperCase(); if(!symbol)return {success:false,message:"An exact symbol is required."}; const item=await saveTrader(userId,"journal",{symbol,direction:args.direction??"other",setup:args.setup??null,notes:args.notes??null,source_execution_id:executionId,idempotency_key:key}); return {success:true,message:`Saved your ${symbol} journal entry.`,item}; }
  if(name==="list_trading_journal") { const items=await listTrader(userId,"journal"); return {success:true,message:items.length?items.slice(0,10).map((item:any)=>`${item.symbol} · ${item.direction}`).join("\n"):"Your trading journal is empty.",items}; }
  if(name==="save_trading_analysis") { const content=String(args.content??"").trim(); if(!content)return {success:false,message:"Analysis content is required."}; const item=await saveTrader(userId,"analysis",{symbol:args.symbol?String(args.symbol).toUpperCase():null,content,notes:args.notes??null,source_execution_id:executionId,idempotency_key:key}); return {success:true,message:"Saved the educational chart analysis.",item}; }
  const entries=await listTrader(userId,"journal"); return {success:true,message:entries.length?`Your journal has ${entries.length} entries. Review the saved results; no performance claim is inferred from missing data.`:"Your trading journal is empty.",entries};
}
