import { NextResponse } from "next/server";
import JSZip from "jszip";

function safe(v:any) {
  return String(v ?? "").replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

export async function POST(req:Request) {
  const { demo } = await req.json();

  if (!demo) {
    return NextResponse.json({ error:"Missing demo" }, { status:400 });
  }

  const slug = demo.slug || "alma-demo";
  const zip = new JSZip();

  zip.file("package.json", JSON.stringify({
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start"
    },
    dependencies: {
      "@tailwindcss/postcss": "latest",
      "lucide-react": "latest",
      "next": "latest",
      "react": "latest",
      "react-dom": "latest",
      "tailwindcss": "latest",
      "typescript": "latest"
    },
    devDependencies: {}
  }, null, 2));

  zip.file("next.config.ts", `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`);

  zip.file("tsconfig.json", JSON.stringify({
    compilerOptions: {
      target: "ES2017",
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "react-jsx",
      incremental: true,
      paths: {
        "@/*": ["./*"]
      }
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
    exclude: ["node_modules"]
  }, null, 2));

  zip.file("postcss.config.mjs", `const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
`);

  zip.file("app/globals.css", `@import "tailwindcss";

* {
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background: #02040a;
  color: white;
}
`);

  zip.file("app/layout.tsx", `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${safe(demo.title)}",
  description: "Generated by ALMA Launch Studio"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`);

  zip.file("components/GeneratedDemo.tsx", `"use client";

const demo = ${JSON.stringify(demo, null, 2)};

export default function GeneratedDemo() {
  const hero = demo.sections?.find((s:any)=>s.type === "hero");
  const table = demo.sections?.find((s:any)=>s.type === "mock_dashboard");
  const features = demo.sections?.find((s:any)=>s.type === "features");
  const stats = demo.sections?.find((s:any)=>s.type === "stats");
  const pricing = demo.sections?.find((s:any)=>s.type === "pricing");

  return (
    <main className="min-h-screen overflow-hidden bg-[#02040a] text-white">
      <div className="fixed inset-0 bg-[linear-gradient(to_right,rgba(255,255,255,.045)_1px,transparent_1px),linear-gradient(to_bottom,rgba(255,255,255,.045)_1px,transparent_1px)] bg-[size:64px_64px]" />
      <div className="fixed left-1/2 top-0 h-[720px] w-[720px] -translate-x-1/2 rounded-full bg-blue-500/20 blur-[140px]" />

      <section className="relative z-10 mx-auto max-w-7xl px-6 py-10">
        <nav className="mb-20 flex items-center justify-between rounded-[1.75rem] border border-white/10 bg-white/[0.045] px-6 py-4 shadow-2xl backdrop-blur-2xl">
          <strong>{demo.title}</strong>
          <div className="hidden gap-8 text-sm text-white/55 md:flex">
            {(demo.nav || []).map((n:string)=><span key={n}>{n}</span>)}
          </div>
          <button className="rounded-full bg-white px-5 py-2 text-sm font-bold text-black">
            Launch
          </button>
        </nav>

        <section className="mb-24">
          <p className="mb-4 text-xs font-bold tracking-[0.25em] text-blue-300">
            {hero?.eyebrow || "AI GENERATED DEMO"}
          </p>

          <h1 className="max-w-5xl bg-gradient-to-r from-white via-blue-100 to-blue-400 bg-clip-text text-6xl font-semibold leading-[0.88] tracking-[-0.075em] text-transparent md:text-8xl">
            {hero?.headline}
          </h1>

          <p className="mt-6 max-w-2xl text-lg leading-8 text-white/55">
            {hero?.subheadline}
          </p>

          <div className="mt-8 flex flex-wrap gap-4">
            <button className="rounded-full bg-blue-500 px-6 py-3 font-bold shadow-[0_0_45px_rgba(59,130,246,.45)]">
              Start Demo
            </button>
            <button className="rounded-full border border-white/10 bg-white/[0.06] px-6 py-3 font-bold">
              View Details
            </button>
          </div>
        </section>

        <section className="mb-20 rounded-3xl border border-blue-400/20 bg-blue-950/20 shadow-[0_0_90px_rgba(37,99,235,.20)]">
          <div className="flex justify-between border-b border-white/10 p-4 text-xs font-bold tracking-widest text-white/40">
            <span>{table?.title || "Live Product Preview"}</span>
            <span className="text-cyan-300">ONLINE</span>
          </div>

          {(table?.rows || []).map((row:any, i:number)=>(
            <div key={i} className="grid grid-cols-4 border-b border-white/5 p-4 text-sm">
              <strong>{row[0]}</strong>
              <span className="text-white/50">{row[1]}</span>
              <span className="text-blue-300">{row[2]}</span>
              <span className="text-emerald-300">{row[3]}</span>
            </div>
          ))}
        </section>

        <section className="mb-20">
          <h2 className="mb-8 text-center text-5xl font-semibold tracking-[-0.06em]">
            {features?.title || "Premium features"}
          </h2>

          <div className="grid gap-4 md:grid-cols-3">
            {(features?.cards || []).slice(0,6).map((card:any, i:number)=>(
              <div key={i} className="rounded-2xl border border-white/10 bg-white/[0.045] p-6 backdrop-blur-xl">
                <h3 className="font-bold">{card.title}</h3>
                <p className="mt-2 text-sm leading-6 text-white/50">{card.description}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="mb-20 grid gap-4 md:grid-cols-4">
          {(stats?.stats || []).map((stat:any, i:number)=>(
            <div key={i} className="rounded-2xl border border-white/10 bg-white/[0.04] p-5">
              <p className="text-xs uppercase tracking-widest text-white/40">{stat[0]}</p>
              <p className="mt-2 text-3xl font-bold">{stat[1]}</p>
            </div>
          ))}
        </section>

        {pricing?.plans && (
          <section className="mb-20">
            <h2 className="mb-8 text-center text-5xl font-semibold tracking-[-0.06em]">
              {pricing.title || "Pricing"}
            </h2>

            <div className="grid gap-4 md:grid-cols-3">
              {pricing.plans.slice(0,3).map((plan:any, i:number)=>(
                <div key={i} className="rounded-3xl border border-white/10 bg-white/[0.045] p-6">
                  <p className="font-bold">{plan.name}</p>
                  <p className="mt-2 text-4xl font-black text-blue-300">{plan.price}</p>
                  <div className="mt-5 space-y-2 text-sm text-white/50">
                    {plan.features?.map((f:string)=><p key={f}> {f}</p>)}
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        <section className="rounded-[2rem] border border-white/10 bg-gradient-to-br from-blue-500/20 to-white/[0.03] p-12 text-center">
          <h2 className="text-5xl font-semibold tracking-[-0.06em]">
            Ready to launch?
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-white/55">
            This demo was generated by ALMA Launch Studio.
          </p>
          <button className="mt-8 rounded-full bg-white px-8 py-4 font-bold text-black">
            Get Started
          </button>
        </section>
      </section>
    </main>
  );
}
`);

  zip.file("app/page.tsx", `import GeneratedDemo from "@/components/GeneratedDemo";

export default function Home() {
  return <GeneratedDemo />;
}
`);

  zip.file("README.md", `# ${safe(demo.title)}

Generated by ALMA Launch Studio.

## Run locally

\`\`\`bash
npm install
npm run dev
\`\`\`

## Deploy to Vercel

1. Upload this folder to GitHub.
2. Go to Vercel.
3. Click **Add New Project**.
4. Import your GitHub repo.
5. Click **Deploy**.

No Vercel token needed.
`);

  const content = await zip.generateAsync({ type:"uint8array" });

  return new NextResponse(content.buffer as ArrayBuffer, {
    status:200,
    headers:{
      "Content-Type":"application/zip",
      "Content-Disposition":`attachment; filename="${slug}-next-project.zip"`
    }
  });
}
